[package]
name = "simplemad-test"
version = "0.1.0"
edition = "2021"

[dependencies]
simplemad = "0.9.0"

# [patch.crates-io]
# simplemad = { path = "../simplemad/simplemad" }
# simplemad_sys = { path = "../simplemad/simplemad_sys" }
